### ISSUE TITLE
Can I just use number or strings instead of date strings?

### ISSUE THREAD

**Issue by tylerdd** [sherubthakur/react-horizontal-timeline#30] opened 2017-10-18 07:52 UTC

**Comment by sherubthakur** [comment] 2017-10-18 10:25
@tylerdd  That is not the intended behaviour, but I am open to a PR which will implement such a feature. i.e. instead of a date array it should take in an array of objects with each object having a relative position value and a label (or something like that).

i.e. from `[ <data-1> , <date-2>]` to `[{"value": <date> or number, "label": null or <string>}]` for null it should default to the value, which is required in this case. 

Thoughts?

**Comment by sherubthakur** [comment] 2018-04-30 21:45
Closing this. Feel free to open if you want to work on this.

**Closed by sherubthakur** 2018-04-30 21:45 UTC
Labels: feature-request
