### ISSUE TITLE
Non-clickable dates

### ISSUE THREAD

**Issue by BradMcGovern** [sherubthakur/react-horizontal-timeline#33] opened 2017-12-29 15:17 UTC
I'm using this solely for a list of dates and labels that users can scroll through, it's not changing pages with a date selection or anything. So it'd be nice if there was an not clickable option for the dates so that the pointer doesn't appear and dots don't change color when highlighted. (the left/right scroll arrows still need to be clickable of course)

**Comment by philmetzger** [comment] 2018-01-04 09:14
Yeah I am also looking for something similar, like the solid green dot is fixed on a date, and when i click on another date, it remains where it was yet i can see more meta info for the other date i have.

Basically the green dot doesnt change unless you specify it to.

**Comment by sherubthakur** [comment] 2018-01-05 02:40
Interesting but I am afraid that is not the intended behaviour. @Nickman87 thoughts?

**Comment by Nickman87** [comment] 2018-01-05 08:36
@philmetzger As you have to provide the index to the timeline yourself, what you propose is currently possible with the component. Just handle the `indexClick` callback and don't change the index prop unless you want it to change.

As for @BradMcGovern, this is currently not supported but could be added with some sort of read-only property I guess? If I may ask, what is the usecase for having a fully interactive timeline except for clicking on it to activate a date? Is there an 'active' date at all or just a plain list of dates on the timeline?

**Comment by BradMcGovern** [comment] 2018-01-09 17:35
I don't need a fully-interactive timeline, just a timeline and this made a nice looking one for what I'm doing. Basically creating a lot of tiles for individual projects. Each project has a set of dates, and I'm using this timeline on the bottom of the tile to illustrate the dates, with the line filled up to the most recent date passed

![image](https://user-images.githubusercontent.com/11986035/34734340-0a466c88-f531-11e7-9af9-6d9249e4ae64.png)

**Comment by sherubthakur** [comment] 2018-04-30 21:48
I believe this is outside the scope of this project (i.e. feature to only allow scrollable dates).

**Closed by sherubthakur** 2018-04-30 21:48 UTC
Labels: technical-support
