### ISSUE TITLE
Cannot read property 'distance' of undefined

### ISSUE THREAD

**Issue by alexkendall** [sherubthakur/react-horizontal-timeline#22] opened 2017-03-30 19:17 UTC
Getting this error.
Uncaught TypeError: Cannot read property 'distance' of undefined

**Comment by Nickman87** [comment] 2017-03-31 08:21
Can you give an example of the props you are passing in?

**Comment by chezhe** [comment] 2017-05-14 12:54
just as the demo
```
<HorizontalTimeline
          indexClick={(index) => {
            this.setState({ value: index, previous: this.state.value });
          }}
          values={ ['2014-11-01','2017-02-28'] } />
```

**Comment by Nickman87** [comment] 2017-05-15 06:20
@chezhe Did you provide a `index` prop? I don't think it is defaulting to 0 correctly so that might explain this issue?

**Comment by m-adil** [comment] 2017-05-29 01:56
@alexkendall any progress? I'm also facing the same issue, no idea where the problem lies.

@chezhe I think you're using wrong format for the `values` as its  `mm/dd/yyyy` as defined on [the ReadMe page](https://github.com/sherubthakur/react-horizontal-timeline)

**Comment by m-adil** [comment] 2017-05-29 03:08
got the problem. We need to define `index` first as:
```
<HorizontalTimeline
    index={this.state.value}
    indexClick={(index) => {
        this.setState({ value: index, previous: this.state.value });
    }}
    values={ VALUES} />
```

**Comment by m-adil** [comment] 2017-05-29 12:17
I think the documentation is missing details. It gives the understanding that all we have to do is to include [npm package for the timeline](https://www.npmjs.com/package/react-horizontal-timeline) in our code and use the sample code as given in the readme page and interestingly this isn't enough. I first got that [index declaration error](https://github.com/sherubthakur/react-horizontal-timeline/issues/22#issuecomment-304563439) and now I'm getting a timeline like this:
<img width="842" alt="screen shot 2017-05-29 at 5 14 21 pm" src="https://cloud.githubusercontent.com/assets/10314241/26549413/63af9d76-4492-11e7-8870-36d1a980aef2.png">

**Comment by Nickman87** [comment] 2017-05-31 19:37
@m-adil The default index is not working as intended so you indeed need to specify the initial 0 index as well.
If you just copied the example, you should not forget to fill in the VALUES array, as in the example code in the readme it is empty.
`const VALUES = [ /* The date strings go here */ ];`

You should add some dates in the YYYY-MM-DD format like so:
`const VALUES = [ '2016-01-01', '2016-03-01', 2017-01-10' ];`

You could also check the demo in the repository to get a more advanced idea of how to use the timeline: https://github.com/sherubthakur/react-horizontal-timeline/tree/master/demos

I've updated the readme to reflect/solve the issues you posted here.

**Comment by m-adil** [comment] 2017-06-01 00:49
Thanks for the update @Nickman87. Yeah I'd filled the values array with my custom dates in the same format.

Sure I'll look into the demo and will let you know with the updates (if any).

**Comment by gnyani** [comment] 2017-07-04 16:16
@m-adil  even I am seeing an empty horizontal-timeline without any dates on it. What did you to resolve the issue? I added index={this.state.value} prop to horizontal timeline.

**Comment by m-adil** [comment] 2017-07-07 14:21
@gnyani It hadn't resolved. I'd not actually used horizontal timeline in the current milestone as these issues were taking time and i was short of time so I'm currently using a custom one. Planning to move back to this in next milestone or whenever i get time.

**Comment by Nickman87** [comment] 2017-07-07 15:27
@gnyani Could you post sample code so we can try to identify the issue?

**Comment by sherubthakur** [comment] 2017-07-08 09:18
@Nickman87 @m-adil @gnyani I also tried to use the code and it looks like there is some issue that is leading to you seeing an empty timeline.

Here are the steps I took:
1. Bootstrap a project using `create-reat-app`.
2. Install `react-horizontal-timeline` using `yarn add react-horizontal-timeline`.
3. Install `bootstrap`.
3. Use the following snippet.
```
 import React, { Component } from 'react';
import HorizontalTimeline from 'react-horizontal-timeline';
import logo from './logo.svg';
import './App.css';
import 'bootstrap/dist/css/bootstrap.css';


const VALUES = ['01/01/1994', '08/31/1996', '05/02/2002']

class App extends Component {
  state = { value: 0, previous: 0 };
  render() {
    return (
      <div className="App">
          <HorizontalTimeline
            indexClick={(index) => {
              this.setState({ value: index, previous: this.state.value });
            }}
            values={ VALUES }
          />
        <div className='text-center'>
          {/* any arbitrary component can go here */}    
          {this.state.value}
        </div>
      </div>
    );
  }
}

export default App;
```
4. You will run into the following issue.
Issue 1: Cannot read property `distance` of undefined.
Fix/Hack: also provide index prop. (This should not have happend, unsure why you need to provide this prop).
`            index={this.state.value}
`

5.  Then you will see something like @m-adil pointed out in his comment.
Issue2: The timeline does not render properly.
Fix/Hack: Add a div around the timeline
`
              <div style={{ width: '30%', height: '100px', margin: '0 auto' }}>
`

Again I am unsure why this is happening.

i.e this final snippet will work.

```
import React, { Component } from 'react';
import HorizontalTimeline from 'react-horizontal-timeline';
import logo from './logo.svg';
import './App.css';
import 'bootstrap/dist/css/bootstrap.css';


const VALUES = ['01/01/1994', '08/31/1996', '05/02/2002']

class App extends Component {
  state = { value: 0, previous: 0 };
  render() {
    return (
      <div className="App">
        <div style={{ width: '30%', height: '100px', margin: '0 auto' }}>
          <HorizontalTimeline
            index={this.state.value}
            indexClick={(index) => {
              this.setState({ value: index, previous: this.state.value });
            }}
            values={ VALUES }
          />
        </div>
        <div className='text-center'>
          {/* any arbitrary component can go here */}    
          {this.state.value}
        </div>
      </div>
    );
  }
}

export default App;
```
We definitely have 2 issues here and I am pretty uncertain as to why these are happening.

P.S. I have not been doing ~much~ any JS for past half year or so would appreciate any help.

**Comment by sherubthakur** [comment] 2017-07-08 10:07
Looks like the issue is due to #21. Which makes the index prop required. Will update the readme.

**Comment by m-adil** [comment] 2017-07-08 13:20
@sherubthakur nice to see that helpful response 👍 
Is `bootstrap` a pre-requisite here? I'd not known nor read it somewhere in the [docs](https://github.com/sherubthakur/react-horizontal-timeline#react-horizontal-timeline). I'm actually using [ant.design](https://ant.design/) as UI library and can't use bootstrap.

@gnyani Hopefully that response will help you resolving the issue. Please update if you get any success as I'm not currently working on it

**Comment by sherubthakur** [comment] 2017-07-09 11:05
@m-adil bootstrap is not a prerequisite I just used it here.

**Comment by m-adil** [comment] 2017-07-09 11:54
o its fine, it means one can use it and achieve the required results without using bootstrap. I should give it a try some time then

**Comment by gnyani** [comment] 2017-07-17 05:52
@sherubthakur  thank you for the example . 

@m-adil  what I actually did Is I took the working example code from https://codyhouse.co/demo/horizontal-timeline/index.html and removed the stuff which I dont need and added the stuff I need and it started working nicely.

**Comment by m-adil** [comment] 2017-07-17 08:42
@gnyani thanks for the update. I wish I may get time to give it a try asap

**Closed** 2018-02-13 06:28 UTC
Labels: bug
